services:
  api:
    environment:
      - ConnectionStrings__LibraryDatabase=Server=host.docker.internal,1433;Database=LibraryDB;User Id=SA;Password=A&VeryComplex123Password;TrustServerCertificate=true
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=A&VeryComplex123Password
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
